#server:
#  port: 8021
#  server:

spring:
  application:
    name: demo01
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/study1?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #\u521D\u59CB\u5EFA\u7ACB\u8FDE\u63A5\u6570\u91CF
      minIdle: 5  #\u6700\u5C0F\u8FDE\u63A5\u6570\u91CF
      maxActive: 20 #\u6700\u5927\u8FDE\u63A5\u6570\u91CF
      maxWait: 10000  #\u83B7\u53D6\u8FDE\u63A5\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF0C\u6BEB\u79D2
      testOnBorrow: true #\u7533\u8BF7\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      testOnReturn: false #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      timeBetweenEvictionRunsMillis: 60000 #\u914D\u7F6E\u95F4\u9694\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684\u65F6\u95F4\uFF08\u5355\u4F4D\u662F\u6BEB\u79D2\uFF09
      minEvictableIdleTimeMillis: 300000  #\u8FDE\u63A5\u5728\u8FDE\u63A5\u6C60\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09

#  jpa:
#    hibernate:
#      ddl-auto: update  # \u66F4\u65B0\u6216\u8005\u521B\u5EFA\u6570\u636E\u8868\u7ED3\u6784
#    show-sql: true  # \u63A7\u5236\u53F0\u663E\u793Asql
#
  ##配置静态资源访问路径
  mvc:
    static-path-pattern: /res/**
    #更改静态资源的存放位置
  resources:
    static-locations: /static

#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#logging:
#  level:
#    edu.xatu.dao: debug
#
